{{url}}/plugins/nxgt/permissions?after=69787c54e9f0c457c2420719&first=2
Authorization: Bearer {{token}}

###
{{url}}/plugins/nxgt/permissions/69788063ecaee62a4ba7067c
Authorization: Bearer {{token}}

###
POST {{url}}/plugins/nxgt/permissions/search?after=69787c54e9f0c457c2420719&first=2
Content-Type: application/json

{
  "filter": {
    "name": "users.update"
  }
}

###
POST {{url}}/plugins/nxgt/permissions
Content-Type: application/json

{
  "name": "users.delete",
  "description": "Permission to delete users"
}